# Generated by Django 5.0.6 on 2024-05-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='attachments',
            field=models.FileField(blank=True, default='', null=True, upload_to='attachments/'),
        ),
    ]
